# uses nginx as base image
FROM nginx 
# copies helloworld.html of this folder to nginx helloworld.html
COPY helloworld.html /usr/share/nginx/html/helloworld.html
# tells docker to listen to this port
EXPOSE 80
